{% set name = "atlite" %}
{% set version = "0.2.3" %}
{% set sha256 = "c1cf32ec638d0886a9bcd24eae7b730b6926c2f7815a666831d4870f8a473eeb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - python >=3
    - pip
    - six
    - setuptools_scm
  run:
    - python >=3
    - numpy
    - scipy
    - pandas >=0.25
    - xarray >=0.16.2
    - dask >=0.18.0, <2021.04.0
    - rasterio >=1.0
    - shapely
    - netcdf4
    - progressbar2
    - tqdm
    - geopandas
    - yaml
    - requests
    - cdsapi
    - pyproj <=2.0
    - numexpr
    - bottleneck

test:
  imports:
    - atlite

about:
  home: https://github.com/PyPSA/atlite
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Atlite converts climate weather data for Power Systems Analysis
  description: |
    Atlite is a free software, xarray-based Python library for converting
    weather data (such as wind speeds, solar radiation, temperature and
    runoff) into power systems data (such as wind power, solar power, hydro
    power and heating demand time series). It is designed to work with big
    datasets, such as hourly global weather data over several years at spatial
    resolutions down to e.g. 0.1 x 0.1 degree resolution.
  dev_url: https://github.com/PyPSA/atlite

extra:
  recipe-maintainers:
    - coroa
    - FabianHofmann
